### ISSUE TITLE
old reddit?

### ISSUE THREAD

**Issue by somedevreally** [trashhalo/reddit-rss#12]
is there a way to set domain to `old.reddit.com` instead of `reddit.com`?

thanks

**Comment by trashhalo** [comment]
Boom! Urls and comment links go to old.reddit.com Might take a couple of hours to start showing up in your feed. 
 
![Screenshot from 2021-08-09 18 58 35](https://user-images.githubusercontent.com/177491/128784658-2f7d3897-ecd2-4b53-8e36-29e2835f8026.png)
