### ISSUE TITLE
Wrong favicon

### ISSUE THREAD

**Issue by ngirard** [trashhalo/reddit-rss#18]
Hi, and thanks for your work !

Using QuiteRSS on Ubuntu 20.04, I noticed that the favicon associated with a feed coming from https://reddit.0qz.fun is the Github one, instead of the Reddit one.

Looking at the contents of the feed, I found
```xml
<channel>
  ...
  <link>https://github.com/trashhalo/reddit-rss</link>
```
which seems to me to be the reason why.
Is there any reason why not putting the original feed url in `<link>` ?
And in any case, could this favicon problem be solved ?

Thanks in advance,
cheers !

**Comment by trashhalo** [comment]
Would you consider this fixed if I put Reddit's favicon there?

**Comment by ngirard** [comment]
Well sure, given that Reddit-rss' sole purpose is to deal with Reddit !

**Comment by ngirard** [comment]
FWIW, proper Reddit feeds contain
```xml
<icon>https://www.redditstatic.com/icon.png/</icon>
```

**Comment by trashhalo** [comment]
Thanks for the info! Will fix it this weekend.

**Comment by trashhalo** [comment]
@ngirard I switched the link to be reddit. Can you see if you get the correct favicon? might need to quit and restart client
