### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Saad-Mehr** [trashhalo/reddit-rss#22]
It appears that your server is down. Is it because the costs are too high?

**Comment by nikhilCad** [comment]
Try self-hosting on heroku.

I had to add this line in go.mod to make it work though
// +heroku goVersion go1.14

**Comment by trashhalo** [comment]
What!!! It went down?? No its effectively free for me. Let me see what happened.

**Comment by Saad-Mehr** [comment]
![Screenshot_20210402-105555.jpg](https://user-images.githubusercontent.com/64493078/113440844-09015780-93a2-11eb-950b-5ea5ef5dcec8.jpg) This is what I see whenever I try to connect to the domain. No pressure from me as it doesn't affect me that much

**Comment by trashhalo** [comment]
FIXED! Sorry about that ya'll
