### ISSUE TITLE
It has stopped working

### ISSUE THREAD

**Issue by SatyamSSJ10** [trashhalo/reddit-rss#26]
Error:
invalid character '<' looking for beginning of value

**Comment by trashhalo** [comment]
Bad news :( Reddit has blocked me. I emailed them at the address it gave to appeal.

**Comment by SatyamSSJ10** [comment]
> Bad news :( Reddit has blocked me. I emailed them at the address it gave to appeal.

Any way I can help like creating another API? It's really necessary for me

**Comment by nikhilCad** [comment]
> > Bad news :( Reddit has blocked me. I emailed them at the address it gave to appeal.
> 
> Any way I can help like creating another API? It's really necessary for me

I think only the domain might be blocked. You should be able to deploy it to Heroku using the deploy on Heroku button in wiki and then use the new domain.

**Comment by SatyamSSJ10** [comment]
> > > Bad news :( Reddit has blocked me. I emailed them at the address it gave to appeal.
> > 
> > 
> > Any way I can help like creating another API? It's really necessary for me
> 
> I think only the domain might be blocked. You should be able to deploy it to Heroku using the deploy on Heroku button in wiki and then use the new domain.

No, I even hosted my own instance but same error

**Comment by trashhalo** [comment]
The block seems to have something to do with how the go code is making the http request. If I make the same request with the same user agent with curl it some how works. There might be a way around the block like if we change the url or user agent slightly

**Comment by SatyamSSJ10** [comment]
> The block seems to have something to do with how the go code is making the http request. If I make the same request with the same user agent with curl it some how works. There might be a way around the block like if we change the url or user agent slightly

I'm amateur at such things I barely know coding but I know some technical stuffs cause I've been messing with bots and stuffs all the time.
Btw I used Windows 10 Home, to host it and got same result

**Comment by trashhalo** [comment]
@SatyamSSJ10 I've managed to bypass the block and reddit.0qz.fun is running once again.

**Comment by SatyamSSJ10** [comment]
> @SatyamSSJ10 I've managed to bypass the block and reddit.0qz.fun is running once again.

Thanks
