### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by SatyamSSJ10** [trashhalo/reddit-rss#28]
I tried opening one of the RSS link, it is showing network connection rest

**Comment by littabird** [comment]
No one response to you?
May be this project has been abandon. 
Can the author please confirm?

**Comment by SatyamSSJ10** [comment]
> No one response to you?
> May be this project has been abandon.
> Can the author please confirm?

It hasn't been abandoned, I talked to the author 4 days before I opened this thread.

**Comment by trashhalo** [comment]
Not abandoned just busy. I'll try to triage issue today

**Comment by trashhalo** [comment]
https://reddit.0qz.fun back online. Also, I believe the Heroku versions should be working again. Let me know if it does
