### ISSUE TITLE
RSS down for weeks now?

### ISSUE THREAD

**Issue by littabird** [trashhalo/reddit-rss#29]
Is this wonderful script still supported? It has been down for weeks now.

I did try using the installer Heroku, surprisingly, it's also down/not working.
Now I wonder if this script has been banned by Heroku or what?

May I ask how can I host this on a Linux sharedhosting? I asked around, no one seems to know.

**Comment by trashhalo** [comment]
Its back online.

**Comment by littabird** [comment]
Thanks trashhalo.

Do you mind to tell what's wrong? 
Was your server banned due to overcapacity?
Can you make a version for me to host a Linux/Apache based server? (I don't know how to mess with a Heroku or whatever hutech "cloud" server).?
