### ISSUE TITLE
Please add option linking comments to i.reddit.com and old.reddit.com instead of www.reddit.com

### ISSUE THREAD

**Issue by nikhilCad** [trashhalo/reddit-rss#31]
www.reddit.com has a popup asking to download there app after you open few of their posts. So please add a tiny option to link the **comments** to i.reddit.com and old.reddit.com instead, which are lighter and don't show the popup.

Note that you can take the link of a reddit thread and remove "www" with "i" and "old" to easily switch between reddit sites.

**Comment by trashhalo** [comment]
Do you think I should swap out all comment links to old.reddit.com? Or make it so you need to pass an extra query param?

**Comment by nikhilCad** [comment]
Must be fine to switch all together. The mobile layout of www.reddit.com is made horrible with all those popus to make people download the official app

**Comment by trashhalo** [comment]
Super easy. Ill ship a change tonight.

**Comment by nikhilCad** [comment]
This will also close #12

**Comment by trashhalo** [comment]
Boom! Urls and comment links go to old.reddit.com Might take a couple of hours to start showing up in your feed. 
 
![Screenshot from 2021-08-09 18 58 35](https://user-images.githubusercontent.com/177491/128784658-2f7d3897-ecd2-4b53-8e36-29e2835f8026.png)

**Comment by ryanmcgrath** [comment]
Old issue but wanted to comment since it's probably more relevant here context-wise: `i.reddit.com` is dead, but you can actually still access it by appending `.i` to the end of any URL.

Dunno if it's worth updating this to reflect that~
