### ISSUE TITLE
embedded video?

### ISSUE THREAD

**Issue by somedevreally** [trashhalo/reddit-rss#37]
first of all thanks for libreddit instance, it works perfect. @nexus-uw 

when the reddit post has image, it looks good. but if the post has youtube or streamable video it wont show up in tt-rss
is it just me?
sample feed https://reddit.0qz.fun/r/formula1.json

thanks @trashhalo

**Comment by jadedgnome** [comment]
v.redd.it works but I don't get any thumbnail images.
gfycat.com works but I don't get thumbnails either
vimeo, imgur, and redgifs media aren't embedded, nor are there thumbnails.

**Comment by trashhalo** [comment]
![Screenshot 2023-02-05 134600](https://user-images.githubusercontent.com/177491/216838670-72c0d391-7cbe-4cec-822f-88a9cdadaf84.jpg)

Shipped a change to support way more video sites. Hopefully that helps 🤞
