### ISSUE TITLE
Score Limit stopped working

### ISSUE THREAD

**Issue by myblackbeard** [trashhalo/reddit-rss#46]
The score limit stopped working around 10 or so hours ago and all posts are coming into the feed unfiltered.

**Comment by trashhalo** [comment]
Shoot. I merged a breaking change last night that renamed the field to scoreLimit wouldn't be hard to change the urls of your feed to use the new name or I can revert to give everyone time to move over.

https://github.com/trashhalo/reddit-rss/pull/45

In the future I wonder what a good way would be to communicate with the people that use this feed before changing stuff. 🤔

**Comment by myblackbeard** [comment]
Ah no worries I'll change my feed, thanks a lot for all the work!

**Comment by butter-radish** [comment]
> In the future I wonder what a good way would be to communicate with the people that use this feed before changing stuff.

Like the other user said, I think mentioning breaking changes prominently on the README here for a while should be fine. This GitHub repo is where every user of the application and the instance you host will come for support, and the people who still use the service (and the rate limit) will definitely come here in the next couple days when they notice the issue; and all issues going forward.

**Comment by glottisfaun0000** [comment]
so many broken feeds...🥲

**Comment by trashhalo** [comment]
💥 https://github.com/trashhalo/reddit-rss/discussions/47

You can now follow `https://github.com/trashhalo/reddit-rss/discussions/categories/announcements.atom` on your feed reader to get announcements.
