### ISSUE TITLE
display username in rss feed

### ISSUE THREAD

**Issue by jadedgnome** [trashhalo/reddit-rss#52]
usernames aren't shown in posts. that information is relevant especially in RSS readers with a rule/filtering engine.

**Comment by trashhalo** [comment]
Done! I also made it a clickable link
![Screenshot 2023-02-05 142519](https://user-images.githubusercontent.com/177491/216840408-6a9bc0b6-4e87-4ce5-93f4-3ac443b36d90.jpg)

**Comment by butter-radish** [comment]
Why not have the posters username in the Author field instead? That would be easier to parse and script. And I miss being able to skip to the first link in the body to get to the comments of a post.
