### ISSUE TITLE
Will the changes to the reddit API impact this project?

### ISSUE THREAD

**Issue by chloyster** [trashhalo/reddit-rss#58]
Basically title. Curious if this utilizes the reddit API, or utilizes anything else that uses the API and if that will impact the project.

**Comment by trashhalo** [comment]
😭 ya I'm shutting the shared service down by the end of the month

https://www.reddit.com/r/rss/comments/13x6dd0/shutting_down_reddit_rss/

**Comment by chloegix** [comment]
😭

Thanks for all your work. Devastating.

**Comment by chloegix** [comment]
So self hosting could be an option? Would we be able to put in our own API key?

**Comment by chloegix** [comment]
Amazing 🙏

Thank you for all your work on this so far

**Comment by trashhalo** [comment]
better late than never?

https://github.com/trashhalo/reddit-rss?tab=readme-ov-file#oauth
