### ISSUE TITLE
Selfhosted build is not working

### ISSUE THREAD

**Issue by tapatianbeast** [trashhalo/reddit-rss#62]
Since yesterday

**Comment by trashhalo** [comment]
Do you have any information on what not working means that might help me debug what's going on?

**Comment by tapatianbeast** [comment]
1:C 13 Mar 2024 07:13:23.191 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:signal-handler (1711174106) Received SIGTERM scheduling shutdown...
1:M 23 Mar 2024 06:08:27.012 # Redis is now ready to exit, bye bye...
1:C 23 Mar 2024 06:08:41.293 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

**Comment by trashhalo** [comment]
New release up that I believe will mitigate the issue you have. You are going to need to use the oauth / apps setup thats detailed in the readme. If you hit any issues let me know so I can update the readme.

https://github.com/trashhalo/reddit-rss?tab=readme-ov-file#oauth

Please close issue if you are good.
