### ISSUE TITLE
Body text doesn't appear

### ISSUE THREAD

**Issue by issue-maker** [trashhalo/reddit-rss#7]
When the post doesn't have an image or doesn't link an article feed shows nothing. Just the title, I can't see the body text of the post.

How to reproduce:
Just grab the feed of a subreddit where people mostly ask questions like r/fossdroid

**Comment by trashhalo** [comment]
I just pushed a commit that will enable this feature. Depending on your feed reader you will start to see this behaviour in the next day or so as the cache clears out.
