### ISSUE TITLE
Videos do not get linked on crossposts

### ISSUE THREAD

**Issue by Leavever** [trashhalo/reddit-rss#8]
There are almost no linked videos on crosspost-heavy subreddits like r/dumbasseswithlighters

**Comment by trashhalo** [comment]
I'll take a look this weekend! thanks for letting me know

**Comment by trashhalo** [comment]
I found the issue and pushed a fix. When a video was cross posted to another subreddit the video url was in a different location. I really appreciate you bringing this up. Fix pushed to production you should see it update in the next 24 hours?

**Comment by Leavever** [comment]
Thank You :)
