### ISSUE TITLE
Stopped working. Site is gone, no longer redirects to announcement post.

### ISSUE THREAD

**Issue by issue-maker** [trashhalo/reddit-rss#9]
While I tried to get the RSS feed of a user I realized feed no longer worked, I tried to enter the domain reddit.0qz.fun to see did I wrote it correctly or not but browser threw an error saying it couldn't reach the site (DNS_PROBE_FINISHED_NXDOMAIN). When I checked my feeds I realised I entered it correctly, this also explained why I wasn't getting as much stuff on my feed when I refreshed.

**Comment by trashhalo** [comment]
OH NO!! I accidentally deleted the dns record yesterday.

Thanks for letting me know, I put it back might take an hour or so to show up again.
